# Turn on validation so we can use import:
version: ~> 1.0

services:
  - mongodb
  - postgresql

before_script:
    - psql -c 'create database mosql;' -U postgres

env:
  - MONGOSQL_TEST_SQL=postgres://localhost/mosql

script:
- rake test